name: Test and Build Web

on:
  pull_request:
  push:
    branches: ['main']

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
     
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build
