name: Test and Build Anchor

on:
  pull_request:
  push:
    branches: ['main']

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - uses: metadaoproject/setup-anchor@v2
        with:
          anchor-version: '0.30.1'
          node-version: '20'
          solana-cli-version: '1.18.17'

      - name: Generate new keypair
        run: solana-keygen new --no-bip39-passphrase

      - name: Set solana target cluster to local
        run: solana config set --url http://localhost:8899

      - name: Check solana config
        run: solana config get

      - run: bun run anchor build
        shell: bash

      - run: bun run anchor test
        shell: bash
