name: Test and Build Web

on:
  pull_request:
  push:
    branches: ['main']

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Bun
        run: curl -fsSL https://bun.sh/install | bash
        env:
          BUN_INSTALL: /home/runner/.bun

      - name: Configure Bun
        run: |
          echo "$HOME/.bun/bin" >> $GITHUB_PATH
          source "$HOME/.bashrc"
          which bun

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build
